### ISSUE TITLE
Move code to 'lein-junit' org

### ISSUE THREAD

**Issue by febeling** [lein-junit/lein-junit#29]
I propose to move this repo to the org named 'lein-junit' (just grabbed it proactively).

I'm no longer involved myself. And I feel it's better to have a place that's not linked to me personally, because then it's more obvious that contributors work towards a common cause.

Make sense? Possible with reasonable effort for Clojars?

**Comment by febeling** [comment]
@r0man Thoughts?

**Comment by r0man** [comment]
@febeling I'm fine with this.

**Comment by febeling** [comment]
Alright, here we are.
